apiVersion: skaffold/v1
kind: Config
metadata:
  name: recipe-tracker-frontend
build:
  artifacts:
  - image: jbankes/recipe-tracker-frontend
deploy:
  kubectl:
    manifests:
    - k8s/recipe-tracker-frontend-deployment.yaml
    - k8s/recipe-tracker-frontend-service.yaml
